### ISSUE TITLE
1.0 Milestone Goals

### ISSUE THREAD

**Issue by IceSelkie** [IceSelkie/billbot-baggins#1]
The goal for a 1.0 milestone is to have a decently stable bot that is able to match the Cox et al. paper in most variants that works online and offline.

### Functionality
- [x] Track basic game state, and player hands
- [x] Understand clues and their positive and negative information
- [x] Track public information (anything that is guaranteed that everyone knows it, and everyone knows everyone knows it, etc.)
- [x] Know what cards are playable, and what has already been played (trash cards)
- [x] Keep track of how many cards of each type are not yet visible (and thus what is critical)
- [x] Eliminate card possibilities by elimination/inference, and propagate them (By copies of each card: public done; By suits and ranks: not for this milestone)
- [ ] Track asymmetric information (be able to act on information that I can see, that isn't yet publicly known)
- [ ] Track game Pace
- [ ] Card flags beyond just "touched" (eg. finessed, cm'd, hatguess-hinted, negative-touched, etc.)

### Variant support
- [x] Basic Variants (eg: Special Ranks, Special Suits, Dual Color, etc)
- [x] Combinations Variants (eg: White Suit + Rainbow 1s)
- [x] Funnels/Chimneys/Matryoshka
- [x] Clue Starved
- [x] Up Or Down
- [x] Sudoku
- [ ] Blind (Done, but implicit empty clues is missing)
- [ ] Synesthesia (Done, but implicit number clue conversion is missing)
- [ ] Alternating clues
- [ ] TIIAH / Throw It In A Hole
- [ ] Cow/Pig
- [ ] Duck (at least so its not crashing; clue inference is complicated so that probably will not be this milestone)

### Hat Guessing (Cox et al)
- [x] Give and understand hat guessing hints and modular arithmetic
- [x] Various action priorities (1 through 7)
- [ ] Simplify Cox implementation (and split off some base class for hat-guessing AI)

### Online Games
- [ ] Login to hanab.live
- [x] Connect to online hanab.live
- [x] Understand join/leave/start/spectate commands
- [x] Understand live hanab.live games as player or spectator
- [x] Understand historical hanab.live games
- [x] Understand historical hanab.live database games
- [x] Play, discard, and clue others
- [ ] Add notes to cards

### Offline Games
- [x] Simulate single game from a given variant and existing deck
- [x] Shuffle a deck with repeatable PRNG
- [x] Support the same variants as online games
- [x] Simulate multiple games in a row
- [ ] Automate winrate statistics by variant

### Game Modifiers
- [ ] Empty Clues (See above: Blind variant's implicit empty clues)
- [ ] Card count modifiers (One Extra Card and One Less Card)
- [ ] All Or Nothing
- [ ] Bottom-Deck Blind-Plays
- [ ] And make all of these work for offline games
(not implementing detrimental characters here)

### Other Todo / Code Cleanup
- [ ] Improve install and setup process
- [ ] Improve/add markdown documentation
- [ ] Improve existing code readability (refactor and add comments)
- [ ] Overhaul imports (use `require` instead of `eval`, if it is even possible to support all the same runtime environments)
- [ ] Improve debugging statements to create less (or more filterable) spam

### Future Hatguesser (not this milestone)
(Future-Hatguesser) Make risky(er) plays in end game, if it can help win the game
(Future-Hatguesser) Predict if others will play/discard/hint for more optimal action choices
(Future-Hatguesser) More intelligent modulo groupings based on what is important (omni/playable/nulls/criticals)
(Future-Hatguesser) Split modulo information across multiple cards instead of wasting when card is partially known
(Future-Hatguesser) Take advantage of additional possible hints (trade positive information for bandwidth): known available hints (eg: holding an omni basically allows empty hints)
(Future-Hatguesser) Take advantage of additional possible hints (trade positive information for bandwidth): what cards are touched (eg: color clue that touches chop or doesn't touch chop)
(Future-Hatguesser) Rebalance what is important to convey (eg: playable, critical, omni/null, etc may be more important to know)
(Future-Hatguesser) Ability to use non-hatguess hints depending on the situation
